### ISSUE TITLE
EXCEPTION ERROR (schedule_resets)

### ISSUE THREAD

**Issue by johnt0991** [johnt0991/TYR-Valheim-Server-Management#13]
Exception in thread Thread-1 (schedule_resets):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "valheim_code_bot.py", line 246, in schedule_resets
UnboundLocalError: cannot access local variable 'reset_process' where it is not associated with a value

**Comment by johnt0991** [comment]
did not happen on launch before server process was ran, only occured after reopening TYR when after server was booted up

**Comment by johnt0991** [comment]
getting error now before even launching the server

Exception in thread Thread-3 (schedule_resets):
Traceback (most recent call last):
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "i:\coding\valheim server\valheim_code_bot.py", line 246, in schedule_resets
    active_processes.remove(reset_process)
                            ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'reset_process' where it is not associated with a value

**Comment by johnt0991** [comment]
after reviewing line 246, it appears the that script tried to close active_processes via `active_processes.remove(reset_process)` without any value associated to active process.

this need to be under a variable to check if process is active first and then if not, skip.  if logic under the else may fix

**Comment by johnt0991** [comment]
restructuring reset process:  

bugged interation:

`            # Track reset thread as an active process (even though it's not a subprocess)
            reset_process = threading.Thread(target=start_batch_script, daemon=True)
            
            # Add the thread to the active threads list
            active_processes.append(reset_process)
            
            # Manually treat the thread as an active process
            send_to_process_tab(f"Scheduled reset subprocess started (Thread ID: {reset_process.ident}, Name: {reset_process.name}).")

            reset_process.start()

            # Wait for the thread to complete before removing it
            reset_process.join()  # This blocks the current thread until reset_process finishes

            time.sleep(120)  # Wait 2 minutes to ensure the server is stopped before restarting
        else:
            # If reset scheduling is disabled, sleep briefly before checking again
            time.sleep(60)
            
            # Remove the thread from the active threads list after it finishes
            active_processes.remove(reset_process)`

**Comment by johnt0991** [comment]
updated after the else and provided a variable to check if the server files are currently active and set global variable

else:
            # If reset scheduling is disabled, sleep briefly before checking again
            time.sleep(60)
            if server_running == True:
                # Remove the thread from the active threads list after it finishes
                active_processes.remove(reset_process)

**Comment by johnt0991** [comment]
Although previous solution patched the known reset_process bug a rewrite removed bug potential.

-no longer threading the start_batch_script function since it was already being opened in a subprocess.
-added error handling to help troubleshoot future bugs.
-removed process marking since threading has been removed.  
-added additional action tab messages for progress markers during restarts.

```def schedule_resets():
    """Schedule server resets at the specified interval."""
    global reset_enabled, reset_interval, reset_start_time, next_reset_time, program_running, server_running
    while program_running:  # This ensures the loop will stop when the program ends
        if reset_enabled:
            
            now = datetime.now()
            next_reset = datetime.combine(now.date(), reset_start_time)
            
            while next_reset <= now:
                next_reset += timedelta(hours=reset_interval)

            next_reset_time = next_reset
            time_to_wait = (next_reset - now).total_seconds()
            print(f"Next reset scheduled at: {next_reset_time}. Waiting {time_to_wait / 3600:.2f} hours.")

            # Notify on Discord 15 minutes before reset
            if time_to_wait > 900:
                threading.Timer(time_to_wait - 900, lambda: send_to_discord(
                    f"Server will restart at {next_reset.strftime('%Y-%m-%d %H:%M')}. 15 minutes remaining."
                )).start()

            time.sleep(time_to_wait)

            send_to_discord("Server is restarting. Please wait until the server is back up to reconnect.")
            send_to_action_tab("Server is restarting")
            try:
                stop_server()
                send_to_action_tab("Server successfully shut down.  Will begin reboot in 30 seconds.")
                threading.Timer(30).start()
                send_to_action_tab("Beginning Server Reboot.")
                start_batch_script()
            except Exception as e:
                send_to_action_tab(f"Error Restarting Server.  Please manually shut down. Error: {e}")

            time.sleep(120)  # Wait 2 minutes to ensure the server is stopped before restarting
        else:
            # If reset scheduling is disabled, sleep briefly before checking again
            time.sleep(60)```

**Comment by johnt0991** [comment]
STILL GETTING THE DAMN ERROR

Exception in thread Thread-10 (schedule_resets):
Traceback (most recent call last):
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "C:\Users\johnt\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "i:\coding\valheim server\valheim_code_bot.py", line 217, in schedule_resets
    send_to_discord("Server is restarting. Please wait until the server is back up to reconnect.")

**Comment by johnt0991** [comment]
schedule resets is being called as a seperate thread in the create_gui fnct.  working on more process checks to correct issue

**Comment by johnt0991** [comment]
corrected issue.  no longer seem to be receiving this error.  

```
def schedule_resets():
    """Schedule server resets at the specified interval."""
    global reset_enabled, reset_interval, reset_start_time, next_reset_time, program_running, server_running, time_to_wait
    while program_running:  # This ensures the loop will stop when the program ends
        if reset_enabled:
            
            now = datetime.now()
            next_reset = datetime.combine(now.date(), reset_start_time)
            
            while next_reset <= now:
                next_reset += timedelta(hours=reset_interval)

            next_reset_time = next_reset
            time_to_wait = (next_reset - now).total_seconds()
            print(f"Next reset scheduled at: {next_reset_time}. Waiting {time_to_wait / 3600:.2f} hours.")
            print("Pre - 15 minute check")
            # Notify on Discord 15 minutes before reset
            if time_to_wait > 900:
                threading.Timer(time_to_wait - 900, lambda: send_to_discord(
                    f"Server will restart at {next_reset.strftime('%Y-%m-%d %H:%M')}. 15 minutes remaining."
                )).start()
            print(f"{time_to_wait} pre-sleep time")
            countdown_thread = threading.Thread(target=update_countdown, daemon=True) 
            countdown_thread.start() 
            time.sleep(time_to_wait)
            print("post sleep confirmation")

            send_to_discord("Server is restarting. Please wait until the server is back up to reconnect.")
            send_to_action_tab("Server is restarting")
            try:
                stop_server()
                send_to_action_tab("Server successfully shut down.  Will begin reboot in 30 seconds.")
                threading.Timer(30).start()
                send_to_action_tab("Beginning Server Reboot.")
                start_batch_script()
            except Exception as e:
                send_to_action_tab(f"Error Restarting Server.  Please manually shut down. Error: {e}")

            time.sleep(120)  # Wait 2 minutes to ensure the server is stopped before restarting
        else:
            # If reset scheduling is disabled, sleep briefly before checking again
            time.sleep(2)
```
